name: "lsy.art"
name_en: "lsy.art"
author: "Ezra"
author_en: "Ezra"
description: "A Developer's Faux Pas"
url: "https://meniny.github.io/lsy.art"
email: "admin@picsew.cn"
tel: "8613111112831"
github_url: "https://github.com/Meniny/lsy.art"
excerpt_limit: 100
timezone: Asia/Shanghai

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

permalink: /posts/contents/:title/
excerpt_limit: 200

sass:
  sass_dir: "/assets/sass/"
  style: compressed

# Plugins
plugins: [jekyll-paginate,liquid] #jekyll-toc,jekyll-asciidoc]
paginate: 6
paginate_path: "/posts/page/:num"

collections:
  posts:
    output: true
  gallery:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
      cover: '/assets/images/site/home/ezra.png'
      fullscreen: false
      show_title: true
      has_header: false
  - scope:
      path: ""
      type: gallery
    values:
      layout: "album"
      fullscreen: false
      show_title: true
      has_header: false
